### ISSUE TITLE
Spark.variable accesses may overlap

### ISSUE THREAD

**Issue by towynlin** [spark/core-communication-lib#26] opened 2014-09-03 22:49 UTC
We need a test to prove this, but there's good evidence that it happens:

- https://community.spark.io/t/two-variables-return-the-same-value-periodically/5220
- http://community.spark.io/t/spark-variable-frequent-call/6452

**Comment by dmiddlecamp** [comment] 2015-03-26 15:04
also this thread - https://community.spark.io/t/ifttt-recipe-checking-wrong-variabe/10906/3

**Comment by dmiddlecamp** [comment] 2015-03-26 15:05
It's also very easy to prove this:

local cloud / local core
spark monitor core my_var1  
spark monitor core my_var2

make sure the monitor calls are using a very low delay between requests, you'll see variable crossover

**Comment by andyw-lala** [comment] 2015-03-26 15:26
What is the serialization in place to ensure the response is correlated
with the correct request ?

i suspect the answer to that will suggest whether this a code issue or a
protocol issue.

On Thu, Mar 26, 2015 at 10:05 AM, David Middlecamp <notifications@github.com
> wrote:

> It's also very easy to prove this:
>
> local cloud / local core
> spark monitor core my_var1
>
> spark monitor core my_var2
>
> make sure the monitor calls are using a very low delay between requests,
> you'll see variable crossover
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/core-communication-lib/issues/26#issuecomment-86559303>
> .
>



-- 
Andy

**Comment by dmiddlecamp** [comment] 2015-03-26 15:28
The protocol provides for this by tagging each coap message with both a message id and token.  These are supposed to be used when sending responses back to the cloud.  The communications lib in the firmware doesn't tag variable responses with the corresponding request id / token, so it's impossible for the cloud to distinguish which response goes with which request.  So it's a pretty clear "the firmware isn't following the protocol" scenario I think.

**Comment by andyw-lala** [comment] 2015-03-26 15:32
Well, the cloud obviously isn't checking/enforcing them either, so I think
fixing the firmware is required, but not sufficient.

Could be a tricky fix to roll out, if that is the case, perhaps with the
cloud using a heuristic to figure out if it should enforce (new FW) or not
(old FW).

On Thu, Mar 26, 2015 at 10:28 AM, David Middlecamp <notifications@github.com
> wrote:

> The protocol provides for this by tagging each coap message with both a
> message id and token. These are supposed to be used when sending responses
> back to the cloud. The communications lib in the firmware doesn't tag
> variable responses with the corresponding request id / token, so it's
> impossible for the cloud to distinguish which response goes with which
> request. So it's a pretty clear "the firmware isn't following the protocol"
> scenario I think.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/core-communication-lib/issues/26#issuecomment-86569265>
> .
>



-- 
Andy

**Comment by dmiddlecamp** [comment] 2015-03-26 15:39
The cloud listens for a particular token on a get variable response here.  I think I'm remembering that the firmware does include the token, but it gets the tokens confused.

https://github.com/spark/spark-protocol/blob/master/js/clients/SparkCore.js#L619

**Comment by andyw-lala** [comment] 2015-03-26 16:27
If that is the case, the fix would be easier to deploy.

On Thu, Mar 26, 2015 at 10:39 AM, David Middlecamp <notifications@github.com
> wrote:

> The cloud listens for a particular token on a get variable response here.
> I think I'm remembering that the firmware does include the token, but it
> gets the tokens confused.
>
>
> https://github.com/spark/spark-protocol/blob/master/js/clients/SparkCore.js#L619
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/core-communication-lib/issues/26#issuecomment-86577921>
> .
>



-- 
Andy

**Comment by m-mcgowan** [comment] 2015-04-08 03:20
Looking though the code I don't see how the firmware could ever try to mix two requests - once a variable request is received, it's processed through to the end, with the variable response message sent in the same thread of execution using the same token as received in the request. There is only one thread of execution for the protocol in firmware, so server requests are always serialized, and client responses sent before the next server request is processed.

I'm not normally a gambler but I'll put a handful of satoshis down that it's not a firmware bug! :-)

**Comment by dmiddlecamp** [comment] 2015-04-08 04:17
How many satoshis are we talking about?

**Comment by m-mcgowan** [comment] 2015-04-10 06:58
oooh...let's say as many as you can fit in a small bag! ;-)

**Comment by dmiddlecamp** [comment] 2015-04-16 16:10
after digging into this I've found when it happens, it only happens when the message has the tokens:

token fa - 250
token f9 - 249

is it possible the firmware is rotating tokens / truncating instead of going the full 255?

**Comment by andyw-lala** [comment] 2015-04-16 16:15
+1 on that discovery - can you provide more detail on the sequence of
actions ?


On Thu, Apr 16, 2015 at 11:10 AM, David Middlecamp <notifications@github.com
> wrote:

> after digging into this I've found when it happens, it only happens when
> the message has the tokens:
>
> token fa - 250
> token f9 - 249
>
> is it possible the firmware is rotating tokens / truncating instead of
> going the full 255?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/core-communication-lib/issues/26#issuecomment-93774155>
> .
>



-- 
Andy

**Comment by m-mcgowan** [comment] 2015-09-16 21:11
I looked at the protocol code on the cloud side, and found that it registers a callback handler for each request based only on the request name, but not a specific request instance, so two requests in close succession would have the first request's handler overwritten with the second, causing the wrong variable value to be returned to the caller of the first request. 

One small bag of satoshis please David as per our wager! :-)

**Comment by dmiddlecamp** [comment] 2015-09-16 21:18
That function is multiply-re-entrant, and that handler is scoped to that function call.  The callback is added to a list of listeners and not overwritten by concurrent requests.  If that were breaking then I would think we'd see loss of messages everywhere instead of this one case.  Also the open source spark-protocol project is not 100% the same code as what's running in production.

But I won't back down from the challenge, I'll certainly re-scrutinize and test this code per your request!  :)  Do I still get satoshis if I re-test it and don't find bugs?

**Comment by m-mcgowan** [comment] 2015-09-16 22:25
I'm only looking at the local cloud and the spark-protocol module, which we know to also exhibit the problem. I'm looking at the code here: https://github.com/spark/spark-protocol/blob/master/js/clients/SparkCore.js#L615
I'm not seeing how the callback is tied to the token at all, so how are different requests associated with the correct response? The callback passed to listenFor isn't based on token.

**Comment by brycekahle** [comment] 2015-09-16 23:08
@m-mcgowan Perhaps this is what you are looking for? https://github.com/spark/spark-protocol/blob/master/js/clients/SparkCore.js#L507

**Comment by m-mcgowan** [comment] 2015-09-16 23:15
Thanks, yes, I remember seeing that. And then noticing here

https://github.com/spark/spark-protocol/blob/master/js/clients/SparkCore.js#L490

When token is 0 tokenHex will be null and that check is then skipped, meaning the wrong response handler can be invoked.

**Comment by brycekahle** [comment] 2015-09-16 23:51
Oooh, good catch. Because of this https://github.com/spark/spark-protocol/blob/master/js/clients/SparkCore.js#L558 `0` is definitely a possible value. We should be able to reproduce this by requesting 256 variables right? I just confirmed the existence of this bug by writing a quick test program.

**Comment by dmiddlecamp** [comment] 2015-09-17 00:00
that'd do it :)

**Comment by dmiddlecamp** [comment] 2015-09-17 00:00
who owes who satoshis?

**Comment by m-mcgowan** [comment] 2015-09-17 00:04
I won the bet - it wasn't a firmware bug! :-)

**Comment by dmiddlecamp** [comment] 2015-09-17 00:48
well, it's a bug, I'm not sure yet it's the cause of what we've been seeing, so I'll reserve my satoshi payout until I've verified it before / after :)

**Comment by m-mcgowan** [comment] 2015-12-18 19:36
just following up, it was this bug, which was fixed by explicitly checking for undefined rather than using a boolean test.

**Closed by m-mcgowan** 2015-12-18 19:36 UTC
Labels: bug
